// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ApplicationSetListerExpansion allows custom methods to be added to
// ApplicationSetLister.
type ApplicationSetListerExpansion interface{}

// ApplicationSetNamespaceListerExpansion allows custom methods to be added to
// ApplicationSetNamespaceLister.
type ApplicationSetNamespaceListerExpansion interface{}
