// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: server/applicationset/applicationset.proto

// ApplicationSet Service
//
// ApplicationSet Service API performs CRUD actions against applicationset resources

package applicationset

import (
	context "context"
	fmt "fmt"
	v1alpha1 "github.com/argoproj/argo-cd/v2/pkg/apis/applicationset/v1alpha1"
	_ "github.com/argoproj/argo-cd/v2/reposerver/apiclient"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	_ "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ApplicationSetQuery is a query for applicationset resources
type ApplicationSetQuery struct {
	// the applicationsets's name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// forces applicationset reconciliation if set to true
	Refresh string `protobuf:"bytes,2,opt,name=refresh,proto3" json:"refresh,omitempty"`
	// the project names to restrict returned list applicationsets
	Projects []string `protobuf:"bytes,3,rep,name=projects,proto3" json:"projects,omitempty"`
	// when specified with a watch call, shows changes that occur after that particular version of a resource.
	ResourceVersion string `protobuf:"bytes,4,opt,name=resourceVersion,proto3" json:"resourceVersion,omitempty"`
	// the selector to restrict returned list to applications only with matched labels
	Selector string `protobuf:"bytes,5,opt,name=selector,proto3" json:"selector,omitempty"`
	// the repoURL to restrict returned list applications
	Repo                 string   `protobuf:"bytes,6,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationSetQuery) Reset()         { *m = ApplicationSetQuery{} }
func (m *ApplicationSetQuery) String() string { return proto.CompactTextString(m) }
func (*ApplicationSetQuery) ProtoMessage()    {}
func (*ApplicationSetQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_eacb9df0ce5738fa, []int{0}
}
func (m *ApplicationSetQuery) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApplicationSetQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApplicationSetQuery.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApplicationSetQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationSetQuery.Merge(m, src)
}
func (m *ApplicationSetQuery) XXX_Size() int {
	return m.Size()
}
func (m *ApplicationSetQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationSetQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationSetQuery proto.InternalMessageInfo

func (m *ApplicationSetQuery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplicationSetQuery) GetRefresh() string {
	if m != nil {
		return m.Refresh
	}
	return ""
}

func (m *ApplicationSetQuery) GetProjects() []string {
	if m != nil {
		return m.Projects
	}
	return nil
}

func (m *ApplicationSetQuery) GetResourceVersion() string {
	if m != nil {
		return m.ResourceVersion
	}
	return ""
}

func (m *ApplicationSetQuery) GetSelector() string {
	if m != nil {
		return m.Selector
	}
	return ""
}

func (m *ApplicationSetQuery) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

type ApplicationSetResponse struct {
	Project              string                   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Applicationset       *v1alpha1.ApplicationSet `protobuf:"bytes,2,opt,name=applicationset,proto3" json:"applicationset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ApplicationSetResponse) Reset()         { *m = ApplicationSetResponse{} }
func (m *ApplicationSetResponse) String() string { return proto.CompactTextString(m) }
func (*ApplicationSetResponse) ProtoMessage()    {}
func (*ApplicationSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eacb9df0ce5738fa, []int{1}
}
func (m *ApplicationSetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApplicationSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApplicationSetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApplicationSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationSetResponse.Merge(m, src)
}
func (m *ApplicationSetResponse) XXX_Size() int {
	return m.Size()
}
func (m *ApplicationSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationSetResponse proto.InternalMessageInfo

func (m *ApplicationSetResponse) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ApplicationSetResponse) GetApplicationset() *v1alpha1.ApplicationSet {
	if m != nil {
		return m.Applicationset
	}
	return nil
}

type ApplicationSetCreateRequest struct {
	FilePath             string                   `protobuf:"bytes,1,opt,name=filePath,proto3" json:"filePath,omitempty"`
	Applicationset       *v1alpha1.ApplicationSet `protobuf:"bytes,2,opt,name=applicationset,proto3" json:"applicationset,omitempty"`
	Upsert               bool                     `protobuf:"varint,3,opt,name=upsert,proto3" json:"upsert,omitempty"`
	Validate             bool                     `protobuf:"varint,4,opt,name=validate,proto3" json:"validate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ApplicationSetCreateRequest) Reset()         { *m = ApplicationSetCreateRequest{} }
func (m *ApplicationSetCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ApplicationSetCreateRequest) ProtoMessage()    {}
func (*ApplicationSetCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eacb9df0ce5738fa, []int{2}
}
func (m *ApplicationSetCreateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApplicationSetCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApplicationSetCreateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApplicationSetCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationSetCreateRequest.Merge(m, src)
}
func (m *ApplicationSetCreateRequest) XXX_Size() int {
	return m.Size()
}
func (m *ApplicationSetCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationSetCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationSetCreateRequest proto.InternalMessageInfo

func (m *ApplicationSetCreateRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *ApplicationSetCreateRequest) GetApplicationset() *v1alpha1.ApplicationSet {
	if m != nil {
		return m.Applicationset
	}
	return nil
}

func (m *ApplicationSetCreateRequest) GetUpsert() bool {
	if m != nil {
		return m.Upsert
	}
	return false
}

func (m *ApplicationSetCreateRequest) GetValidate() bool {
	if m != nil {
		return m.Validate
	}
	return false
}

type ApplicationSetUpdateRequest struct {
	FilePath             string                   `protobuf:"bytes,1,opt,name=filePath,proto3" json:"filePath,omitempty"`
	Applicationset       *v1alpha1.ApplicationSet `protobuf:"bytes,2,opt,name=applicationset,proto3" json:"applicationset,omitempty"`
	Validate             bool                     `protobuf:"varint,3,opt,name=validate,proto3" json:"validate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ApplicationSetUpdateRequest) Reset()         { *m = ApplicationSetUpdateRequest{} }
func (m *ApplicationSetUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ApplicationSetUpdateRequest) ProtoMessage()    {}
func (*ApplicationSetUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eacb9df0ce5738fa, []int{3}
}
func (m *ApplicationSetUpdateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApplicationSetUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApplicationSetUpdateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApplicationSetUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationSetUpdateRequest.Merge(m, src)
}
func (m *ApplicationSetUpdateRequest) XXX_Size() int {
	return m.Size()
}
func (m *ApplicationSetUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationSetUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationSetUpdateRequest proto.InternalMessageInfo

func (m *ApplicationSetUpdateRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *ApplicationSetUpdateRequest) GetApplicationset() *v1alpha1.ApplicationSet {
	if m != nil {
		return m.Applicationset
	}
	return nil
}

func (m *ApplicationSetUpdateRequest) GetValidate() bool {
	if m != nil {
		return m.Validate
	}
	return false
}

type ApplicationSetDeleteRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cascade              bool     `protobuf:"varint,2,opt,name=cascade,proto3" json:"cascade,omitempty"`
	PropagationPolicy    string   `protobuf:"bytes,3,opt,name=propagationPolicy,proto3" json:"propagationPolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationSetDeleteRequest) Reset()         { *m = ApplicationSetDeleteRequest{} }
func (m *ApplicationSetDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ApplicationSetDeleteRequest) ProtoMessage()    {}
func (*ApplicationSetDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eacb9df0ce5738fa, []int{4}
}
func (m *ApplicationSetDeleteRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApplicationSetDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApplicationSetDeleteRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApplicationSetDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationSetDeleteRequest.Merge(m, src)
}
func (m *ApplicationSetDeleteRequest) XXX_Size() int {
	return m.Size()
}
func (m *ApplicationSetDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationSetDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationSetDeleteRequest proto.InternalMessageInfo

func (m *ApplicationSetDeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplicationSetDeleteRequest) GetCascade() bool {
	if m != nil {
		return m.Cascade
	}
	return false
}

func (m *ApplicationSetDeleteRequest) GetPropagationPolicy() string {
	if m != nil {
		return m.PropagationPolicy
	}
	return ""
}

type ApplicationSetResourceDeleteRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ResourceName         string   `protobuf:"bytes,3,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Group                string   `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	Kind                 string   `protobuf:"bytes,6,opt,name=kind,proto3" json:"kind,omitempty"`
	Force                bool     `protobuf:"varint,7,opt,name=force,proto3" json:"force,omitempty"`
	Orphan               bool     `protobuf:"varint,8,opt,name=orphan,proto3" json:"orphan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationSetResourceDeleteRequest) Reset()         { *m = ApplicationSetResourceDeleteRequest{} }
func (m *ApplicationSetResourceDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ApplicationSetResourceDeleteRequest) ProtoMessage()    {}
func (*ApplicationSetResourceDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eacb9df0ce5738fa, []int{5}
}
func (m *ApplicationSetResourceDeleteRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApplicationSetResourceDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApplicationSetResourceDeleteRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApplicationSetResourceDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationSetResourceDeleteRequest.Merge(m, src)
}
func (m *ApplicationSetResourceDeleteRequest) XXX_Size() int {
	return m.Size()
}
func (m *ApplicationSetResourceDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationSetResourceDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationSetResourceDeleteRequest proto.InternalMessageInfo

func (m *ApplicationSetResourceDeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplicationSetResourceDeleteRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ApplicationSetResourceDeleteRequest) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *ApplicationSetResourceDeleteRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ApplicationSetResourceDeleteRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *ApplicationSetResourceDeleteRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ApplicationSetResourceDeleteRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *ApplicationSetResourceDeleteRequest) GetOrphan() bool {
	if m != nil {
		return m.Orphan
	}
	return false
}

func init() {
	proto.RegisterType((*ApplicationSetQuery)(nil), "applicationset.ApplicationSetQuery")
	proto.RegisterType((*ApplicationSetResponse)(nil), "applicationset.ApplicationSetResponse")
	proto.RegisterType((*ApplicationSetCreateRequest)(nil), "applicationset.ApplicationSetCreateRequest")
	proto.RegisterType((*ApplicationSetUpdateRequest)(nil), "applicationset.ApplicationSetUpdateRequest")
	proto.RegisterType((*ApplicationSetDeleteRequest)(nil), "applicationset.ApplicationSetDeleteRequest")
	proto.RegisterType((*ApplicationSetResourceDeleteRequest)(nil), "applicationset.ApplicationSetResourceDeleteRequest")
}

func init() {
	proto.RegisterFile("server/applicationset/applicationset.proto", fileDescriptor_eacb9df0ce5738fa)
}

var fileDescriptor_eacb9df0ce5738fa = []byte{
	// 697 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xae, 0x6f, 0xda, 0x34, 0x99, 0x7b, 0x75, 0x11, 0x03, 0x54, 0x56, 0xa8, 0xaa, 0xca, 0x95,
	0x50, 0x04, 0xd4, 0x56, 0xc3, 0x06, 0x89, 0x15, 0x7f, 0x02, 0x24, 0x44, 0x8b, 0x2b, 0x58, 0xb0,
	0xa9, 0xa6, 0xe3, 0x53, 0x67, 0x88, 0xeb, 0x19, 0x66, 0x26, 0x86, 0x2c, 0xd8, 0xb0, 0x62, 0xcd,
	0x6b, 0xf0, 0x04, 0xbc, 0x01, 0x2b, 0xc4, 0x23, 0xa0, 0x2e, 0xd8, 0xf1, 0x0e, 0x68, 0xc6, 0x76,
	0x12, 0x3b, 0xd0, 0x74, 0xd1, 0x0a, 0x56, 0x39, 0xdf, 0x78, 0x66, 0xce, 0xf7, 0x9d, 0x73, 0xbe,
	0xd8, 0xe8, 0xaa, 0x02, 0x99, 0x81, 0x0c, 0x88, 0x10, 0x09, 0xa3, 0x44, 0x33, 0x9e, 0x2a, 0xd0,
	0x35, 0xe8, 0x0b, 0xc9, 0x35, 0xc7, 0xff, 0x57, 0x57, 0x3b, 0xab, 0x31, 0xe7, 0x71, 0x02, 0x01,
	0x11, 0x2c, 0x20, 0x69, 0xca, 0x75, 0xfe, 0x24, 0xdf, 0xdd, 0xd9, 0x8e, 0x99, 0xee, 0x0f, 0xf7,
	0x7d, 0xca, 0x0f, 0x03, 0x22, 0x63, 0x2e, 0x24, 0x7f, 0x69, 0x83, 0x4d, 0x1a, 0x05, 0x59, 0x2f,
	0x10, 0x83, 0xd8, 0x9c, 0x54, 0xf5, 0xd4, 0xd9, 0x16, 0x49, 0x44, 0x9f, 0x6c, 0x05, 0x31, 0xa4,
	0x20, 0x89, 0x86, 0xa8, 0xb8, 0xf0, 0xfe, 0x9c, 0x0b, 0x25, 0x08, 0x5e, 0xa8, 0xb1, 0x21, 0xd3,
	0x5c, 0x8e, 0xa6, 0xc2, 0xe2, 0x9a, 0x87, 0x83, 0x9b, 0xca, 0x67, 0xdc, 0xe4, 0x86, 0x37, 0x1a,
	0x52, 0x65, 0xf2, 0x6e, 0x1a, 0x26, 0xf9, 0xd9, 0x29, 0x5e, 0x53, 0x1b, 0x82, 0x6c, 0x86, 0x90,
	0xf7, 0xc9, 0x41, 0x17, 0x6e, 0x4f, 0xc8, 0xef, 0x82, 0x7e, 0x3a, 0x04, 0x39, 0xc2, 0x18, 0x2d,
	0xa6, 0xe4, 0x10, 0x5c, 0x67, 0xdd, 0xe9, 0xb6, 0x43, 0x1b, 0x63, 0x17, 0x2d, 0x4b, 0x38, 0x90,
	0xa0, 0xfa, 0xee, 0x3f, 0x76, 0xb9, 0x84, 0xb8, 0x83, 0x5a, 0x46, 0x09, 0x50, 0xad, 0xdc, 0xc6,
	0x7a, 0xa3, 0xdb, 0x0e, 0xc7, 0x18, 0x77, 0xd1, 0x39, 0x09, 0x8a, 0x0f, 0x25, 0x85, 0xe7, 0x20,
	0x0d, 0x11, 0x77, 0xd1, 0x9e, 0xae, 0x2f, 0x9b, 0x5b, 0x14, 0x24, 0x40, 0x35, 0x97, 0xee, 0x92,
	0xdd, 0x32, 0xc6, 0x86, 0x8f, 0xa9, 0x82, 0xdb, 0xcc, 0xf9, 0x98, 0xd8, 0xfb, 0xe8, 0xa0, 0x95,
	0x2a, 0xf7, 0x10, 0x94, 0x30, 0x1d, 0x30, 0x54, 0x0b, 0x02, 0x85, 0x82, 0x12, 0xe2, 0xd7, 0xa8,
	0x36, 0x02, 0x56, 0xcb, 0xbf, 0xbd, 0x6d, 0x7f, 0xd2, 0x1a, 0xbf, 0x6c, 0x8d, 0x0d, 0xf6, 0x68,
	0xe4, 0x67, 0x3d, 0x5f, 0x0c, 0x62, 0xdf, 0xd4, 0xd4, 0xaf, 0xcd, 0x55, 0xd9, 0x6b, 0xbf, 0x46,
	0xa5, 0x96, 0xc6, 0xfb, 0xee, 0xa0, 0xcb, 0xd5, 0x2d, 0x77, 0x25, 0x10, 0x0d, 0x21, 0xbc, 0x1a,
	0x82, 0xd2, 0x46, 0xfd, 0x01, 0x4b, 0x60, 0x87, 0xe8, 0x7e, 0xc1, 0x79, 0x8c, 0xff, 0x18, 0x69,
	0xbc, 0x82, 0x9a, 0x43, 0xa1, 0x40, 0x6a, 0xb7, 0xb1, 0xee, 0x74, 0x5b, 0x61, 0x81, 0x0c, 0xd9,
	0x8c, 0x24, 0x2c, 0x22, 0x1a, 0x6c, 0x37, 0x5b, 0xe1, 0x18, 0x7b, 0x5f, 0x66, 0x84, 0x3e, 0x13,
	0xd1, 0xdf, 0x2e, 0x74, 0x5a, 0x50, 0xa3, 0x26, 0x68, 0x54, 0xd7, 0x73, 0x0f, 0x12, 0x98, 0xe8,
	0xf9, 0x8d, 0x55, 0x28, 0x51, 0x94, 0x44, 0x60, 0x05, 0xb4, 0xc2, 0x12, 0xe2, 0xeb, 0xe8, 0xbc,
	0x90, 0x5c, 0x90, 0xd8, 0x5e, 0xb6, 0xc3, 0x13, 0x46, 0x47, 0x36, 0x63, 0x3b, 0x9c, 0x7d, 0xe0,
	0xfd, 0x70, 0xd0, 0xc6, 0xcc, 0x88, 0x5b, 0xd3, 0xcc, 0xe7, 0xb0, 0x8a, 0xda, 0xe6, 0x57, 0x09,
	0x42, 0xa1, 0x30, 0xec, 0x64, 0x01, 0x7b, 0xe8, 0xbf, 0xd2, 0x7f, 0x4f, 0xcc, 0xc9, 0x9c, 0x42,
	0x65, 0xcd, 0xa8, 0xc8, 0x2a, 0x96, 0x2d, 0x21, 0xbe, 0x88, 0x96, 0x62, 0xc9, 0x87, 0xa2, 0xf0,
	0x69, 0x0e, 0x0c, 0x8b, 0x01, 0x4b, 0xa3, 0xd2, 0xa4, 0x26, 0x36, 0x3b, 0x0f, 0xb8, 0xa4, 0xe0,
	0x2e, 0xdb, 0x3a, 0xe4, 0xc0, 0xcc, 0x15, 0x97, 0xa2, 0x4f, 0x52, 0xb7, 0x95, 0xcf, 0x55, 0x8e,
	0x7a, 0x1f, 0x96, 0xd0, 0xa5, 0xaa, 0xde, 0x5d, 0x90, 0x19, 0xa3, 0x80, 0xdf, 0x39, 0x68, 0xf1,
	0x31, 0x53, 0x1a, 0x6f, 0xd4, 0x5b, 0xfc, 0x8b, 0xbf, 0xaf, 0xce, 0xee, 0x29, 0xcf, 0x8b, 0xc9,
	0xec, 0x2d, 0xe0, 0xf7, 0x0e, 0x6a, 0xe6, 0xae, 0xc5, 0xd7, 0x8e, 0xa7, 0x51, 0xf1, 0x76, 0xe7,
	0xb4, 0xc7, 0xd7, 0x5b, 0xc0, 0x6f, 0x51, 0xe3, 0x01, 0x9c, 0xb0, 0x1a, 0x67, 0x90, 0xde, 0x54,
	0x22, 0xb7, 0xf5, 0xbc, 0x4a, 0x54, 0xcc, 0x7f, 0x16, 0x54, 0xf6, 0x50, 0x33, 0x37, 0xc3, 0x3c,
	0x26, 0x15, 0xcb, 0x74, 0xae, 0x1c, 0xbf, 0xb9, 0x7c, 0x95, 0x78, 0x0b, 0x77, 0x1e, 0x7d, 0x3e,
	0x5a, 0x73, 0xbe, 0x1e, 0xad, 0x39, 0xdf, 0x8e, 0xd6, 0x9c, 0x17, 0xb7, 0x4e, 0xf6, 0x4d, 0x40,
	0x13, 0x06, 0x69, 0xfd, 0x23, 0x64, 0xbf, 0x69, 0xdf, 0xba, 0x37, 0x7e, 0x06, 0x00, 0x00, 0xff,
	0xff, 0xe4, 0xde, 0x77, 0xea, 0xb3, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApplicationSetServiceClient is the client API for ApplicationSetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApplicationSetServiceClient interface {
	//List returns list of applications
	List(ctx context.Context, in *ApplicationSetQuery, opts ...grpc.CallOption) (*v1alpha1.ApplicationSetList, error)
	//Create creates an applicationset
	Create(ctx context.Context, in *ApplicationSetCreateRequest, opts ...grpc.CallOption) (*v1alpha1.ApplicationSet, error)
	//Get returns an applicationset by name
	Get(ctx context.Context, in *ApplicationSetQuery, opts ...grpc.CallOption) (*v1alpha1.ApplicationSet, error)
	// Update updates an applicationset
	Update(ctx context.Context, in *ApplicationSetUpdateRequest, opts ...grpc.CallOption) (*v1alpha1.ApplicationSet, error)
	// Delete deletes an application set
	Delete(ctx context.Context, in *ApplicationSetDeleteRequest, opts ...grpc.CallOption) (*ApplicationSetResponse, error)
}

type applicationSetServiceClient struct {
	cc *grpc.ClientConn
}

func NewApplicationSetServiceClient(cc *grpc.ClientConn) ApplicationSetServiceClient {
	return &applicationSetServiceClient{cc}
}

func (c *applicationSetServiceClient) List(ctx context.Context, in *ApplicationSetQuery, opts ...grpc.CallOption) (*v1alpha1.ApplicationSetList, error) {
	out := new(v1alpha1.ApplicationSetList)
	err := c.cc.Invoke(ctx, "/applicationset.ApplicationSetService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationSetServiceClient) Create(ctx context.Context, in *ApplicationSetCreateRequest, opts ...grpc.CallOption) (*v1alpha1.ApplicationSet, error) {
	out := new(v1alpha1.ApplicationSet)
	err := c.cc.Invoke(ctx, "/applicationset.ApplicationSetService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationSetServiceClient) Get(ctx context.Context, in *ApplicationSetQuery, opts ...grpc.CallOption) (*v1alpha1.ApplicationSet, error) {
	out := new(v1alpha1.ApplicationSet)
	err := c.cc.Invoke(ctx, "/applicationset.ApplicationSetService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationSetServiceClient) Update(ctx context.Context, in *ApplicationSetUpdateRequest, opts ...grpc.CallOption) (*v1alpha1.ApplicationSet, error) {
	out := new(v1alpha1.ApplicationSet)
	err := c.cc.Invoke(ctx, "/applicationset.ApplicationSetService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationSetServiceClient) Delete(ctx context.Context, in *ApplicationSetDeleteRequest, opts ...grpc.CallOption) (*ApplicationSetResponse, error) {
	out := new(ApplicationSetResponse)
	err := c.cc.Invoke(ctx, "/applicationset.ApplicationSetService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationSetServiceServer is the server API for ApplicationSetService service.
type ApplicationSetServiceServer interface {
	//List returns list of applications
	List(context.Context, *ApplicationSetQuery) (*v1alpha1.ApplicationSetList, error)
	//Create creates an applicationset
	Create(context.Context, *ApplicationSetCreateRequest) (*v1alpha1.ApplicationSet, error)
	//Get returns an applicationset by name
	Get(context.Context, *ApplicationSetQuery) (*v1alpha1.ApplicationSet, error)
	// Update updates an applicationset
	Update(context.Context, *ApplicationSetUpdateRequest) (*v1alpha1.ApplicationSet, error)
	// Delete deletes an application set
	Delete(context.Context, *ApplicationSetDeleteRequest) (*ApplicationSetResponse, error)
}

// UnimplementedApplicationSetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedApplicationSetServiceServer struct {
}

func (*UnimplementedApplicationSetServiceServer) List(ctx context.Context, req *ApplicationSetQuery) (*v1alpha1.ApplicationSetList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedApplicationSetServiceServer) Create(ctx context.Context, req *ApplicationSetCreateRequest) (*v1alpha1.ApplicationSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedApplicationSetServiceServer) Get(ctx context.Context, req *ApplicationSetQuery) (*v1alpha1.ApplicationSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedApplicationSetServiceServer) Update(ctx context.Context, req *ApplicationSetUpdateRequest) (*v1alpha1.ApplicationSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedApplicationSetServiceServer) Delete(ctx context.Context, req *ApplicationSetDeleteRequest) (*ApplicationSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterApplicationSetServiceServer(s *grpc.Server, srv ApplicationSetServiceServer) {
	s.RegisterService(&_ApplicationSetService_serviceDesc, srv)
}

func _ApplicationSetService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationSetQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationSetServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/applicationset.ApplicationSetService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationSetServiceServer).List(ctx, req.(*ApplicationSetQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationSetService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationSetCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationSetServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/applicationset.ApplicationSetService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationSetServiceServer).Create(ctx, req.(*ApplicationSetCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationSetService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationSetQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationSetServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/applicationset.ApplicationSetService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationSetServiceServer).Get(ctx, req.(*ApplicationSetQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationSetService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationSetUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationSetServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/applicationset.ApplicationSetService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationSetServiceServer).Update(ctx, req.(*ApplicationSetUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationSetService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationSetDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationSetServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/applicationset.ApplicationSetService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationSetServiceServer).Delete(ctx, req.(*ApplicationSetDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApplicationSetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "applicationset.ApplicationSetService",
	HandlerType: (*ApplicationSetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ApplicationSetService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ApplicationSetService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ApplicationSetService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ApplicationSetService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ApplicationSetService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/applicationset/applicationset.proto",
}

func (m *ApplicationSetQuery) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApplicationSetQuery) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApplicationSetQuery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Repo) > 0 {
		i -= len(m.Repo)
		copy(dAtA[i:], m.Repo)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.Repo)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Selector) > 0 {
		i -= len(m.Selector)
		copy(dAtA[i:], m.Selector)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.Selector)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ResourceVersion) > 0 {
		i -= len(m.ResourceVersion)
		copy(dAtA[i:], m.ResourceVersion)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.ResourceVersion)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Projects) > 0 {
		for iNdEx := len(m.Projects) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Projects[iNdEx])
			copy(dAtA[i:], m.Projects[iNdEx])
			i = encodeVarintApplicationset(dAtA, i, uint64(len(m.Projects[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Refresh) > 0 {
		i -= len(m.Refresh)
		copy(dAtA[i:], m.Refresh)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.Refresh)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ApplicationSetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApplicationSetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApplicationSetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Applicationset != nil {
		{
			size, err := m.Applicationset.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintApplicationset(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Project) > 0 {
		i -= len(m.Project)
		copy(dAtA[i:], m.Project)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.Project)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ApplicationSetCreateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApplicationSetCreateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApplicationSetCreateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Validate {
		i--
		if m.Validate {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Upsert {
		i--
		if m.Upsert {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Applicationset != nil {
		{
			size, err := m.Applicationset.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintApplicationset(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.FilePath) > 0 {
		i -= len(m.FilePath)
		copy(dAtA[i:], m.FilePath)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.FilePath)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ApplicationSetUpdateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApplicationSetUpdateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApplicationSetUpdateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Validate {
		i--
		if m.Validate {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Applicationset != nil {
		{
			size, err := m.Applicationset.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintApplicationset(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.FilePath) > 0 {
		i -= len(m.FilePath)
		copy(dAtA[i:], m.FilePath)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.FilePath)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ApplicationSetDeleteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApplicationSetDeleteRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApplicationSetDeleteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.PropagationPolicy) > 0 {
		i -= len(m.PropagationPolicy)
		copy(dAtA[i:], m.PropagationPolicy)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.PropagationPolicy)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Cascade {
		i--
		if m.Cascade {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ApplicationSetResourceDeleteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApplicationSetResourceDeleteRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApplicationSetResourceDeleteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Orphan {
		i--
		if m.Orphan {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.Force {
		i--
		if m.Force {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if len(m.Kind) > 0 {
		i -= len(m.Kind)
		copy(dAtA[i:], m.Kind)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.Kind)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Group) > 0 {
		i -= len(m.Group)
		copy(dAtA[i:], m.Group)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.Group)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ResourceName) > 0 {
		i -= len(m.ResourceName)
		copy(dAtA[i:], m.ResourceName)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.ResourceName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintApplicationset(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintApplicationset(dAtA []byte, offset int, v uint64) int {
	offset -= sovApplicationset(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ApplicationSetQuery) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	l = len(m.Refresh)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	if len(m.Projects) > 0 {
		for _, s := range m.Projects {
			l = len(s)
			n += 1 + l + sovApplicationset(uint64(l))
		}
	}
	l = len(m.ResourceVersion)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	l = len(m.Selector)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	l = len(m.Repo)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ApplicationSetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Project)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	if m.Applicationset != nil {
		l = m.Applicationset.Size()
		n += 1 + l + sovApplicationset(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ApplicationSetCreateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FilePath)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	if m.Applicationset != nil {
		l = m.Applicationset.Size()
		n += 1 + l + sovApplicationset(uint64(l))
	}
	if m.Upsert {
		n += 2
	}
	if m.Validate {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ApplicationSetUpdateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FilePath)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	if m.Applicationset != nil {
		l = m.Applicationset.Size()
		n += 1 + l + sovApplicationset(uint64(l))
	}
	if m.Validate {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ApplicationSetDeleteRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	if m.Cascade {
		n += 2
	}
	l = len(m.PropagationPolicy)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ApplicationSetResourceDeleteRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	l = len(m.ResourceName)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	l = len(m.Group)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	l = len(m.Kind)
	if l > 0 {
		n += 1 + l + sovApplicationset(uint64(l))
	}
	if m.Force {
		n += 2
	}
	if m.Orphan {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovApplicationset(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApplicationset(x uint64) (n int) {
	return sovApplicationset(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ApplicationSetQuery) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApplicationset
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApplicationSetQuery: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApplicationSetQuery: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Refresh", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Refresh = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Projects", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Projects = append(m.Projects, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Selector", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Selector = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Repo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Repo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApplicationset(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApplicationset
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ApplicationSetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApplicationset
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApplicationSetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApplicationSetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Project", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Project = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Applicationset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Applicationset == nil {
				m.Applicationset = &v1alpha1.ApplicationSet{}
			}
			if err := m.Applicationset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApplicationset(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApplicationset
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ApplicationSetCreateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApplicationset
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApplicationSetCreateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApplicationSetCreateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilePath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FilePath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Applicationset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Applicationset == nil {
				m.Applicationset = &v1alpha1.ApplicationSet{}
			}
			if err := m.Applicationset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Upsert", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Upsert = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validate", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Validate = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipApplicationset(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApplicationset
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ApplicationSetUpdateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApplicationset
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApplicationSetUpdateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApplicationSetUpdateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilePath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FilePath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Applicationset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Applicationset == nil {
				m.Applicationset = &v1alpha1.ApplicationSet{}
			}
			if err := m.Applicationset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validate", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Validate = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipApplicationset(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApplicationset
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ApplicationSetDeleteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApplicationset
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApplicationSetDeleteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApplicationSetDeleteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cascade", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Cascade = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PropagationPolicy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PropagationPolicy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApplicationset(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApplicationset
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ApplicationSetResourceDeleteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApplicationset
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApplicationSetResourceDeleteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApplicationSetResourceDeleteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Group", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Group = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplicationset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Kind = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Force", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Force = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Orphan", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Orphan = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipApplicationset(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApplicationset
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApplicationset(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApplicationset
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApplicationset
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApplicationset
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApplicationset
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApplicationset
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApplicationset        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApplicationset          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApplicationset = fmt.Errorf("proto: unexpected end of group")
)
