// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/argoproj/argo-cd/v2/pkg/client/clientset/versioned/typed/applicationset/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAppsetV1alpha1 struct {
	*testing.Fake
}

func (c *FakeAppsetV1alpha1) ApplicationSets(namespace string) v1alpha1.ApplicationSetInterface {
	return &FakeApplicationSets{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAppsetV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
